package nezet;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNev = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chbHirlevel = new javax.swing.JCheckBox();
        cmbSzak = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPrgBetoltes = new javax.swing.JMenuItem();
        mnuPrgMentes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPrgKilepes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuPrgBetoltes1 = new javax.swing.JMenuItem();
        mnuPrgMentes1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuPrgKilepes1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Név");

        chbHirlevel.setSelected(true);
        chbHirlevel.setText("hírlevél");

        cmbSzak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--== Kiválasztott szak ==--", "Szoftverfejlesztő", "Rendszergazda", "Szoftverfejlesztő és tesztelő" }));
        cmbSzak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSzakActionPerformed(evt);
            }
        });

        jLabel2.setText("Szak");

        jLabel3.setText("Aktuális konfig");

        jLabel4.setText("Név");

        jLabel5.setText("Konfigurációk");

        jLabel6.setText("Szak");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--== Kiválasztott szak ==--", "Szoftverfejlesztő", "Rendszergazda", "Szoftverfejlesztő és tesztelő" }));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Konfiguráció");

        mnuPrgBetoltes.setText("Betöltés...");
        mnuPrgBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgBetoltesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPrgBetoltes);

        mnuPrgMentes.setText("Mentés...");
        mnuPrgMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgMentesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPrgMentes);
        jMenu1.add(jSeparator1);

        mnuPrgKilepes.setText("Kilépés...");
        mnuPrgKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPrgKilepes);

        jMenu2.setText("Program");

        mnuPrgBetoltes1.setText("Betöltés...");
        mnuPrgBetoltes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgBetoltes1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPrgBetoltes1);

        mnuPrgMentes1.setText("Mentés...");
        mnuPrgMentes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgMentes1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPrgMentes1);
        jMenu2.add(jSeparator2);

        mnuPrgKilepes1.setText("Kilépés...");
        mnuPrgKilepes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgKilepes1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPrgKilepes1);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Program");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cmbSzak, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(chbHirlevel))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSzak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbHirlevel))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPrgKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgKilepesActionPerformed
        kilepes();
    }//GEN-LAST:event_mnuPrgKilepesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //System.out.println("kilépés folyamatban...");
        kilepes();
    }//GEN-LAST:event_formWindowClosing

    private void mnuPrgMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgMentesActionPerformed
        //JFileChooser jfc = new JFileChooser();//Documents könnyvtár
        String hely = System.getProperty("user.dir");
        JFileChooser jfc = new JFileChooser(hely);//aktuális projekt könnyvtár
        
        /* jfc paraméterezése: */
        File kivalasztottFajl = new File(hely + "\\" + txtNev.getText() + ".txt");
        System.out.println("fajl = " + kivalasztottFajl);
        jfc.setSelectedFile(kivalasztottFajl);
        
        /* jfc megjelenítése, vizsgálata */
        int gomb = jfc.showSaveDialog(rootPane);//null | this <-- ez ua, mint rootPane
        
        if (gomb == JFileChooser.APPROVE_OPTION) {
            kivalasztottFajl = jfc.getSelectedFile();
            String fajlElerese = kivalasztottFajl.getAbsolutePath();
            Path path = Path.of(fajlElerese);//hova írjuk
            try {
                Files.writeString(path, tartalom());
            } catch (IOException ex) {
                /* felhasználónak: */
                String msg = "IO hiba!\n" + ex.getMessage();
                JOptionPane.showMessageDialog(rootPane, msg);
                /* fejlesztőnek: */
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        /* a mentés alapszerkezete: */
//        Path path = Path.of("kimenet.txt");//hova írjuk
//        byte[] bytes = jTextField1.getText().getBytes();//mit írunk
//        try {
//            //Files.write(path, bytes);
//            Files.writeString(path, jTextField1.getText());
//        } catch (IOException ex) {// generált kód!!!
//            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_mnuPrgMentesActionPerformed

    private void mnuPrgBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgBetoltesActionPerformed
        /* a beolvasás alapszerkezete: */
        JFileChooser jfc = new JFileChooser(System.getProperty("user.dir"));//aktuális projekt könnyvtár
        int gomb = jfc.showSaveDialog(rootPane);//null | this <-- ez ua, mint rootPane
        if (gomb == JFileChooser.APPROVE_OPTION) {
            File kivalasztottFajl = jfc.getSelectedFile();
            try {
                String adatok = Files.readString(kivalasztottFajl.toPath());
                System.out.println("A beolvasott fájl tartalma: ");
                System.out.println(adatok);
                
                /* sorok feldolgozása */
                String[] sorok = adatok.split("\n");
                String nev = sorok[0].substring(sorok[0].indexOf(" ")+1);
                String strSzam = sorok[1].substring(sorok[1].indexOf("(")+1, sorok[1].length()-1);
                int index = Integer.parseInt(strSzam);
                String strChb = sorok[2].split(" ")[1];
                boolean chb = strChb.startsWith("nem")?false:true;
                
                txtNev.setText(nev);
                cmbSzak.setSelectedIndex(index);
                chbHirlevel.setSelected(chb);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuPrgBetoltesActionPerformed

    private void mnuPrgBetoltes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgBetoltes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPrgBetoltes1ActionPerformed

    private void mnuPrgMentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgMentes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPrgMentes1ActionPerformed

    private void mnuPrgKilepes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgKilepes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPrgKilepes1ActionPerformed

    private void cmbSzakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSzakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSzakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private String tartalom(){
        String nev = txtNev.getText();
        String szak = cmbSzak.getSelectedItem().toString();
        boolean hirlevel = chbHirlevel.isSelected();
        final String SEP=" ";
        return nev+SEP+cmbSzak.getSelectedIndex()+SEP+hirlevel;
    }
    private void kilepes() throws HeadlessException {
        String msg = "Biztos kilépsz?";
        String cim = "KILÉPÉS";
        int msgTip = JOptionPane.QUESTION_MESSAGE;
        int optTip = JOptionPane.YES_NO_OPTION;//.OK_CANCEL_OPTION;
        //JOptionPane.showMessageDialog(this, msg, cim, msgTip);
        int gomb = JOptionPane.showConfirmDialog(rootPane, msg, cim, optTip);
        if (gomb == JOptionPane.YES_OPTION) {
            int hibaKod = 0;
            System.exit(hibaKod);
        }
        
        //System.out.println("gomb = " + gomb);//YES: 0, NO: 1 , X: -1
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbHirlevel;
    private javax.swing.JComboBox<String> cmbSzak;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem mnuPrgBetoltes;
    private javax.swing.JMenuItem mnuPrgBetoltes1;
    private javax.swing.JMenuItem mnuPrgKilepes;
    private javax.swing.JMenuItem mnuPrgKilepes1;
    private javax.swing.JMenuItem mnuPrgMentes;
    private javax.swing.JMenuItem mnuPrgMentes1;
    private javax.swing.JTextField txtNev;
    // End of variables declaration//GEN-END:variables
}
